In [1]:
import re

def is_prime(n):
    """Check if a number is prime."""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True
    

# %% [markdown]
# TEST 
def list_primes_with_indices(file_path):
    primes_with_indices = []
    with open(file_path, 'r') as file:
        index = 1
        for line in file:
            for word in line.split():
                if word.isdigit() and is_prime(int(word)):
                    primes_with_indices.append((index, int(word)))
                    index += 1
    return primes_with_indices

# Example file path (to be replaced with actual file path)
file_path = '/Users/paolopignatelli/Programming/Fundamental Language/Primes/PrimeTextFiles/primes-to-100k.txt'
primes_with_indices = list_primes_with_indices(file_path)
print("Primes with indices:", primes_with_indices)
    

# %% [markdown]
# ## Second Level Primes (Primes of Primes)

# %%
def primes_of_primes(primes_with_indices):
    second_level_primes = []
    for index, prime in primes_with_indices:
        if is_prime(index):
            second_level_primes.append(prime)
    return second_level_primes

# Using the previously generated list of primes with indices
second_level_primes = primes_of_primes(primes_with_indices)
print("Second level primes (primes of primes):", second_level_primes)

Primes with indices: [(1, 2), (2, 3), (3, 5), (4, 7), (5, 11), (6, 13), (7, 17), (8, 19), (9, 23), (10, 29), (11, 31), (12, 37), (13, 41), (14, 43), (15, 47), (16, 53), (17, 59), (18, 61), (19, 67), (20, 71), (21, 73), (22, 79), (23, 83), (24, 89), (25, 97), (26, 101), (27, 103), (28, 107), (29, 109), (30, 113), (31, 127), (32, 131), (33, 137), (34, 139), (35, 149), (36, 151), (37, 157), (38, 163), (39, 167), (40, 173), (41, 179), (42, 181), (43, 191), (44, 193), (45, 197), (46, 199), (47, 211), (48, 223), (49, 227), (50, 229), (51, 233), (52, 239), (53, 241), (54, 251), (55, 257), (56, 263), (57, 269), (58, 271), (59, 277), (60, 281), (61, 283), (62, 293), (63, 307), (64, 311), (65, 313), (66, 317), (67, 331), (68, 337), (69, 347), (70, 349), (71, 353), (72, 359), (73, 367), (74, 373), (75, 379), (76, 383), (77, 389), (78, 397), (79, 401), (80, 409), (81, 419), (82, 421), (83, 431), (84, 433), (85, 439), (86, 443), (87, 449), (88, 457), (89, 461), (90, 463), (91, 467), (92, 479), (93,

In [6]:
def load_primes(file_path):
    with open(file_path, 'r') as file:
        primes = [int(line.strip()) for line in file if line.strip().isdigit()]
    return primes

def list_primes(primes):
    return [(i + 1, prime) for i, prime in enumerate(primes)]

def primes_of_primes(primes, depth=1):
    if depth == 1:
        return [(i, primes[i - 1]) for i in primes if i - 1 < len(primes)]
    else:
        previous_primes = primes_of_primes(primes, depth - 1)
        return [(i, primes[i - 1]) for _, i in previous_primes if i - 1 < len(primes)]

# Example usage
file_path = "PrimeTextFiles/primes-to-100k.txt"  # Replace with your file path
primes = load_primes(file_path)

# List the first 10 primes in the desired format
prime_list = list_primes(primes)[:10]

# List the primes of primes
primes_of_primes_list = primes_of_primes(primes)[:10]

print("First 10 primes:", prime_list)
print("Primes of primes:", primes_of_primes_list)

#  EXPERIMENT 1 - 1st level primes




First 10 primes: [(1, 2), (2, 3), (3, 5), (4, 7), (5, 11), (6, 13), (7, 17), (8, 19), (9, 23), (10, 29)]
Primes of primes: [(2, 3), (3, 5), (5, 11), (7, 17), (11, 31), (13, 41), (17, 59), (19, 67), (23, 83), (29, 109)]


In [7]:
def load_primes(file_path):
    with open(file_path, 'r') as file:
        primes = [int(line.strip()) for line in file if line.strip().isdigit()]
    return primes

def list_primes(primes):
    return [(i + 1, prime) for i, prime in enumerate(primes)]

def primes_of_primes(primes, depth=1):
    if depth == 1:
        return [(i, primes[i - 1]) for i in primes if i - 1 < len(primes)]
    else:
        previous_primes = primes_of_primes(primes, depth - 1)
        return [(i, primes[i - 1]) for _, i in previous_primes if i - 1 < len(primes)]

# Example usage
file_path = "PrimeTextFiles/primes-to-100k.txt"  # Replace with your file path
primes = load_primes(file_path)

def format_primes(prime_list, primes_of_primes_list):
    return [(prime_list[i][0], prime_list[i][1], primes_of_primes_list[i][1]) for i in range(len(primes_of_primes_list))]

# Applying the function to get the desired format
formatted_primes = format_primes(prime_list, primes_of_primes_list)
print("Formatted primes:", formatted_primes)
#  EXPERIMENT 1 - 1st level primes

Formatted primes: [(1, 2, 3), (2, 3, 5), (3, 5, 11), (4, 7, 17), (5, 11, 31), (6, 13, 41), (7, 17, 59), (8, 19, 67), (9, 23, 83), (10, 29, 109)]


In [12]:
def load_primes(file_path):
    with open(file_path, 'r') as file:
        primes = [int(line.strip()) for line in file if line.strip().isdigit()]
    return primes

def list_primes(primes):
    return [(i + 1, prime) for i, prime in enumerate(primes)]

def primes_of_primes(primes, depth=1):
    if depth == 1:
        return [(i, primes[i - 1]) for i in primes if i - 1 < len(primes)]
    else:
        previous_primes = primes_of_primes(primes, depth - 1)
        return [(i, primes[i - 1]) for _, i in previous_primes if i - 1 < len(primes)]

# Example usage
file_path = "PrimeTextFiles/primes-to-100k.txt"  # Replace with your file path
primes = load_primes(file_path)

def format_primes(prime_list, primes_of_primes_list):
    return [(prime_list[i][0], prime_list[i][1], primes_of_primes_list[i][1]) for i in range(len(primes_of_primes_list))]

# Applying the function to get the desired format
formatted_primes = format_primes(prime_list, primes_of_primes_list)
print("Formatted primes:", formatted_primes)
#  EXPERIMENT 1 Recursive primes of primes 
#  TEST TES TEST TEST TEST
def indexed_recursive_primes_of_primes(primes, depth):
    def helper(current_depth, current_primes):
        if current_depth == 1:
            return [(i + 1, prime) for i, prime in enumerate(current_primes)]
        else:
            lower_primes = helper(current_depth - 1, current_primes)
            return [(i, current_primes[i - 1]) for i, _ in lower_primes if i - 1 < len(current_primes)]

    result = helper(depth, primes)
    return [(i + 1, res) for i, res in enumerate(result)]

# Example usage for depth 3 (primes of primes of primes)
indexed_depth_3_primes = indexed_recursive_primes_of_primes(primes, 3)
print("Indexed depth 3 primes:", indexed_depth_3_primes)


#   END TEST END



Formatted primes: [(1, 2, 3), (2, 3, 5), (3, 5, 11), (4, 7, 17), (5, 11, 31), (6, 13, 41), (7, 17, 59), (8, 19, 67), (9, 23, 83), (10, 29, 109)]
Indexed depth 3 primes: [(1, (1, 2)), (2, (2, 3)), (3, (3, 5)), (4, (4, 7)), (5, (5, 11)), (6, (6, 13)), (7, (7, 17)), (8, (8, 19)), (9, (9, 23)), (10, (10, 29)), (11, (11, 31)), (12, (12, 37)), (13, (13, 41)), (14, (14, 43)), (15, (15, 47)), (16, (16, 53)), (17, (17, 59)), (18, (18, 61)), (19, (19, 67)), (20, (20, 71)), (21, (21, 73)), (22, (22, 79)), (23, (23, 83)), (24, (24, 89)), (25, (25, 97)), (26, (26, 101)), (27, (27, 103)), (28, (28, 107)), (29, (29, 109)), (30, (30, 113)), (31, (31, 127)), (32, (32, 131)), (33, (33, 137)), (34, (34, 139)), (35, (35, 149)), (36, (36, 151)), (37, (37, 157)), (38, (38, 163)), (39, (39, 167)), (40, (40, 173)), (41, (41, 179)), (42, (42, 181)), (43, (43, 191)), (44, (44, 193)), (45, (45, 197)), (46, (46, 199)), (47, (47, 211)), (48, (48, 223)), (49, (49, 227)), (50, (50, 229)), (51, (51, 233)), (52, (52, 

In [14]:
import numpy as np

# 2D Matrix
list_2d = [(1, 2), (2, 3), (3, 5), (4, 7)]
matrix_2d = np.array(list_2d)

# 3D Matrix
list_3d = [(1, 2, 3), (2, 3, 5), (3, 5, 11), (4, 7, 17)]
matrix_3d = np.array(list_3d)

# Display the matrices
print("2D Matrix:\n", matrix_2d)
print("3D Matrix:\n", matrix_3d)


2D Matrix:
 [[1 2]
 [2 3]
 [3 5]
 [4 7]]
3D Matrix:
 [[ 1  2  3]
 [ 2  3  5]
 [ 3  5 11]
 [ 4  7 17]]


In [17]:
import numpy as np

# Define a complete list of primes up to the desired range
# For example, let's take the first few primes:
primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]

# Primes as a 1D matrix
primes_1d = np.array(primes)

# Primes of primes as a 2D matrix
# We use a list comprehension, ensuring indices are within bounds
primes_of_primes = [(prime, primes[prime - 1]) for prime in primes if prime - 1 < len(primes)]
primes_of_primes_2d = np.array(primes_of_primes)

# Now, primes_1d is a 1D matrix (vector) of primes
# and primes_of_primes_2d is a 2D matrix of primes and their corresponding primes of primes
print("Primes as a 1D matrix:\n", primes_1d)
print("Primes of primes as a 2D matrix:\n", primes_of_primes_2d)



Primes as a 1D matrix:
 [ 2  3  5  7 11 13 17 19 23 29 31 37]
Primes of primes as a 2D matrix:
 [[ 2  3]
 [ 3  5]
 [ 5 11]
 [ 7 17]
 [11 31]]
